services:
  - type: web
    name: retrait-attestation-diplome
    env: python
    plan: free  # ou "starter" si tu es sur une offre payante
    buildCommand: |
      pip install -r requirements.txt
      flask db upgrade
    startCommand: flask run --host=0.0.0.0 --port=10000
    envVars:
      - key: FLASK_APP
        value: run.py
      - key: FLASK_ENV
        value: production
