services:
  - type: web
    name: retrait-attestation-diplome
    env: python
    plan: free

    buildCommand: |
      pip install -r requirements.txt
      flask db upgrade  # Migrations uniquement

    startCommand: |
      python setup_data.py && flask run --host=0.0.0.0 --port=10000

    envVars:
      - key: FLASK_APP
        value: run.py
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        value: sqlite:///app/app.db
