"""Ajout du champ fichier_piece

Revision ID: 0080ba6ea9d8
Revises: 43b3f210330e
Create Date: 2025-06-05 12:25:33.889706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0080ba6ea9d8'
down_revision = '43b3f210330e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document')
    with op.batch_alter_table('demande', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fichier_piece', sa.String(length=200), nullable=True))
        batch_op.alter_column('fichier_recu',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=200),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('demande', schema=None) as batch_op:
        batch_op.alter_column('fichier_recu',
               existing_type=sa.String(length=200),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
        batch_op.drop_column('fichier_piece')

    op.create_table('document',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('filename', sa.VARCHAR(length=150), nullable=False),
    sa.Column('annee', sa.VARCHAR(length=10), nullable=True),
    sa.Column('filiere', sa.VARCHAR(length=100), nullable=True),
    sa.Column('utilisateur_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
