"""Ajout de la colonne date_upload à DocumentAdmin

Revision ID: 167925d06aef
Revises: 7289d8ae84f8
Create Date: 2025-06-07 17:51:11.444279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '167925d06aef'
down_revision = '7289d8ae84f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents_admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_upload', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents_admin', schema=None) as batch_op:
        batch_op.drop_column('date_upload')

    # ### end Alembic commands ###
