"""Ajout du champ lu_par_admin dans MessageContact

Revision ID: 26c82a59df1a
Revises: 97b1c0434b35
Create Date: 2025-06-05 15:16:05.752307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26c82a59df1a'
down_revision = '97b1c0434b35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message_contact', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lu_par_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message_contact', schema=None) as batch_op:
        batch_op.drop_column('lu_par_admin')

    # ### end Alembic commands ###
