"""Ajout et correction des modèles

Revision ID: 34b833892384
Revises: 26c82a59df1a
Create Date: 2025-06-05 18:47:48.953845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34b833892384'
down_revision = '26c82a59df1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('messages_contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('sujet', sa.String(length=200), nullable=True),
    sa.Column('contenu', sa.Text(), nullable=True),
    sa.Column('date_envoi', sa.DateTime(), nullable=True),
    sa.Column('reponse', sa.Text(), nullable=True),
    sa.Column('date_reponse', sa.DateTime(), nullable=True),
    sa.Column('lu_par_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('references_quittances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    op.create_table('resultats_academiques',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matricule', sa.String(length=20), nullable=False),
    sa.Column('annee_scolaire', sa.String(length=20), nullable=False),
    sa.Column('niveau', sa.String(length=10), nullable=False),
    sa.Column('valide', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('demandes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_demande', sa.String(length=50), nullable=True),
    sa.Column('fichier_acte_naissance', sa.String(length=200), nullable=True),
    sa.Column('fichier_carte_etudiant', sa.String(length=200), nullable=True),
    sa.Column('fichier_releve_notes', sa.String(length=200), nullable=True),
    sa.Column('fichier_demande_au_doyen', sa.String(length=200), nullable=True),
    sa.Column('fichier_recu', sa.String(length=200), nullable=True),
    sa.Column('fichier_piece', sa.String(length=200), nullable=True),
    sa.Column('numero_quittance', sa.String(length=50), nullable=True),
    sa.Column('quittance_valide', sa.Boolean(), nullable=True),
    sa.Column('annee_scolaire', sa.String(length=20), nullable=True),
    sa.Column('date_demande', sa.DateTime(), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=True),
    sa.Column('raison_refus', sa.String(length=255), nullable=True),
    sa.Column('utilisateur_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents_admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=150), nullable=False),
    sa.Column('date_upload', sa.DateTime(), nullable=True),
    sa.Column('demande_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['demande_id'], ['demandes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('message_contact')
    op.drop_table('demande')
    op.drop_table('admin')
    op.drop_table('resultat_academique')
    op.drop_table('reference_quittance')
    op.drop_table('document_admin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_admin',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('filename', sa.VARCHAR(length=150), nullable=False),
    sa.Column('demande_id', sa.INTEGER(), nullable=False),
    sa.Column('date_upload', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['demande_id'], ['demande.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reference_quittance',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('numero', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    op.create_table('resultat_academique',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('matricule', sa.VARCHAR(length=20), nullable=False),
    sa.Column('annee_scolaire', sa.VARCHAR(length=20), nullable=False),
    sa.Column('niveau', sa.VARCHAR(length=10), nullable=False),
    sa.Column('valide', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('prenom', sa.VARCHAR(length=100), nullable=False),
    sa.Column('mot_de_passe', sa.VARCHAR(length=128), nullable=False),
    sa.Column('nom', sa.VARCHAR(length=100), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('demande',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('type_demande', sa.VARCHAR(length=50), nullable=True),
    sa.Column('fichier_acte_naissance', sa.VARCHAR(length=200), nullable=True),
    sa.Column('fichier_carte_etudiant', sa.VARCHAR(length=200), nullable=True),
    sa.Column('fichier_releve_notes', sa.VARCHAR(length=200), nullable=True),
    sa.Column('fichier_demande_au_doyen', sa.VARCHAR(length=200), nullable=True),
    sa.Column('numero_quittance', sa.VARCHAR(length=50), nullable=True),
    sa.Column('quittance_valide', sa.BOOLEAN(), nullable=True),
    sa.Column('annee_scolaire', sa.VARCHAR(length=20), nullable=True),
    sa.Column('date_demande', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('statut', sa.VARCHAR(length=20), nullable=True),
    sa.Column('raison_refus', sa.VARCHAR(length=255), nullable=True),
    sa.Column('utilisateur_id', sa.INTEGER(), nullable=True),
    sa.Column('fichier_recu', sa.VARCHAR(length=200), nullable=True),
    sa.Column('fichier_piece', sa.VARCHAR(length=200), nullable=True),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message_contact',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nom', sa.VARCHAR(length=100), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('sujet', sa.VARCHAR(length=200), nullable=True),
    sa.Column('contenu', sa.TEXT(), nullable=True),
    sa.Column('date_envoi', sa.DATETIME(), nullable=True),
    sa.Column('reponse', sa.TEXT(), nullable=True),
    sa.Column('date_reponse', sa.DATETIME(), nullable=True),
    sa.Column('lu_par_admin', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('documents_admin')
    op.drop_table('demandes')
    op.drop_table('resultats_academiques')
    op.drop_table('references_quittances')
    op.drop_table('messages_contact')
    op.drop_table('admins')
    # ### end Alembic commands ###
