"""Ajout du champ fichier_recu dans Demande

Revision ID: 43b3f210330e
Revises: cf0da20acd70
Create Date: 2025-06-05 11:36:52.153616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43b3f210330e'
down_revision = 'cf0da20acd70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('demande', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fichier_recu', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('demande', schema=None) as batch_op:
        batch_op.drop_column('fichier_recu')

    # ### end Alembic commands ###
