"""Add type_document column to documents_admin

Revision ID: 578bacf1726a
Revises: 34b833892384
Create Date: 2025-06-05 22:11:12.493109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '578bacf1726a'
down_revision = '34b833892384'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents_admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_document', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents_admin', schema=None) as batch_op:
        batch_op.drop_column('type_document')

    # ### end Alembic commands ###
