"""Initial migration

Revision ID: 67011fa34267
Revises: 
Create Date: 2025-06-03 18:17:17.680255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67011fa34267'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('etudiants_reference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('matricule', sa.String(length=20), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=True),
    sa.Column('annee', sa.String(length=10), nullable=True),
    sa.Column('filiere', sa.String(length=100), nullable=True),
    sa.Column('compte_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('matricule')
    )
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expediteur', sa.String(length=10), nullable=False),
    sa.Column('contenu', sa.Text(), nullable=False),
    sa.Column('date_envoi', sa.DateTime(), nullable=False),
    sa.Column('conversation_id', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('matricule', sa.String(length=50), nullable=True),
    sa.Column('lu_par_admin', sa.Boolean(), nullable=True),
    sa.Column('lu_par_etudiant', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resultat_academique',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matricule', sa.String(length=20), nullable=False),
    sa.Column('annee_scolaire', sa.String(length=20), nullable=False),
    sa.Column('niveau', sa.String(length=10), nullable=False),
    sa.Column('valide', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('utilisateurs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('matricule', sa.String(length=20), nullable=True),
    sa.Column('numero', sa.String(length=20), nullable=True),
    sa.Column('annee', sa.String(length=10), nullable=True),
    sa.Column('filiere', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('demande',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_demande', sa.String(length=50), nullable=True),
    sa.Column('fichier_acte_naissance', sa.String(length=200), nullable=True),
    sa.Column('fichier_carte_etudiant', sa.String(length=200), nullable=True),
    sa.Column('fichier_releve_notes', sa.String(length=200), nullable=True),
    sa.Column('fichier_demande_au_doyen', sa.String(length=200), nullable=True),
    sa.Column('numero_quittance', sa.String(length=50), nullable=True),
    sa.Column('quittance_valide', sa.Boolean(), nullable=True),
    sa.Column('annee_scolaire', sa.String(length=20), nullable=True),
    sa.Column('date_demande', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=True),
    sa.Column('raison_refus', sa.String(length=255), nullable=True),
    sa.Column('utilisateur_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('filename', sa.String(length=150), nullable=False),
    sa.Column('annee', sa.String(length=10), nullable=True),
    sa.Column('filiere', sa.String(length=100), nullable=True),
    sa.Column('utilisateur_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=150), nullable=False),
    sa.Column('demande_id', sa.Integer(), nullable=False),
    sa.Column('date_upload', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['demande_id'], ['demande.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document_admin')
    op.drop_table('document')
    op.drop_table('demande')
    op.drop_table('utilisateurs')
    op.drop_table('resultat_academique')
    op.drop_table('message')
    op.drop_table('etudiants_reference')
    op.drop_table('admin')
    # ### end Alembic commands ###
