"""Ajout ou modification de modèles

Revision ID: 7289d8ae84f8
Revises: e995df8eaf08
Create Date: 2025-06-05 23:37:56.200289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7289d8ae84f8'
down_revision = 'e995df8eaf08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents_admin', schema=None) as batch_op:
        batch_op.drop_column('etudiant_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents_admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('etudiant_id', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
