"""Ajout table ReferenceQuittance

Revision ID: 7984dcfa185e
Revises: 67011fa34267
Create Date: 2025-06-04 18:27:06.794596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7984dcfa185e'
down_revision = '67011fa34267'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reference_quittance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reference_quittance')
    # ### end Alembic commands ###
