"""ajout table MessageContact

Revision ID: 97b1c0434b35
Revises: 0080ba6ea9d8
Create Date: 2025-06-05 14:39:27.156852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97b1c0434b35'
down_revision = '0080ba6ea9d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('sujet', sa.String(length=200), nullable=True),
    sa.Column('contenu', sa.Text(), nullable=True),
    sa.Column('date_envoi', sa.DateTime(), nullable=True),
    sa.Column('reponse', sa.Text(), nullable=True),
    sa.Column('date_reponse', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('message')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('expediteur', sa.VARCHAR(length=10), nullable=False),
    sa.Column('contenu', sa.TEXT(), nullable=False),
    sa.Column('date_envoi', sa.DATETIME(), nullable=False),
    sa.Column('conversation_id', sa.VARCHAR(length=120), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('matricule', sa.VARCHAR(length=50), nullable=True),
    sa.Column('lu_par_admin', sa.BOOLEAN(), nullable=True),
    sa.Column('lu_par_etudiant', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('message_contact')
    # ### end Alembic commands ###
