"""Ajout champ visible_admin

Revision ID: c61587c4c8d1
Revises: 2eb1f9c8240a
Create Date: 2025-07-18 13:32:05.508624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c61587c4c8d1'
down_revision = '2eb1f9c8240a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages_contact', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visible_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages_contact', schema=None) as batch_op:
        batch_op.drop_column('visible_admin')

    # ### end Alembic commands ###
