"""Ajout du champ prenom dans Admin

Revision ID: cf0da20acd70
Revises: 7984dcfa185e
Create Date: 2025-06-05 11:10:50.840815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf0da20acd70'
down_revision = '7984dcfa185e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prenom', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('mot_de_passe', sa.String(length=128), nullable=False))
        batch_op.alter_column('nom',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('nom',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('mot_de_passe')
        batch_op.drop_column('prenom')

    # ### end Alembic commands ###
