"""Ajout des colonnes à DocumentAdmin

Revision ID: e995df8eaf08
Revises: 578bacf1726a
Create Date: 2025-06-05 22:16:34.584900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e995df8eaf08'
down_revision = '578bacf1726a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents_admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('annee', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('filiere', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('etudiant_id', sa.Integer(), nullable=True))
        batch_op.alter_column('demande_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('date_upload')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents_admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_upload', sa.DATETIME(), nullable=True))
        batch_op.alter_column('demande_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('etudiant_id')
        batch_op.drop_column('filiere')
        batch_op.drop_column('annee')

    # ### end Alembic commands ###
